# Generated by Django 3.2.5 on 2022-10-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishes_at',
            new_name='published_at',
        ),
    ]
